package tileconv_test

import (
	"testing"

	"github.com/edorfaus/tileconv"
)

func TestRowPlanarSize(t *testing.T) {
	check := func(bd tileconv.BitDepth, want int) {
		t.Helper()
		tp := tileconv.RowPlanar{BitDepth: bd}
		got := tp.Size()
		if got != want {
			t.Errorf("depth %v size: want %v, got %v", bd, want, got)
		}
	}
	check(tileconv.BD1, 8*1)
	check(tileconv.BD2, 8*2)
	check(tileconv.BD3, 8*3)
	check(tileconv.BD4, 8*4)
	check(tileconv.BD5, 8*5)
	check(tileconv.BD6, 8*6)
	check(tileconv.BD7, 8*7)
	check(tileconv.BD8, 8*8)
}

func TestRowPlanarEncode(t *testing.T) {
	// This table was generated by reformatting the result of calling
	// math/rand.New(rand.NewSource(0)).Read(buf) on a 8*8-long slice.
	srcPix := [][]uint8{
		{0x01, 0x94, 0xFD, 0xC2, 0xFA, 0x2F, 0xFC, 0xC0},
		{0x41, 0xD3, 0xFF, 0x12, 0x04, 0x5B, 0x73, 0xC8},
		{0x6E, 0x4F, 0xF9, 0x5F, 0xF6, 0x62, 0xA5, 0xEE},
		{0xE8, 0x2A, 0xBD, 0xF4, 0x4A, 0x2D, 0x0B, 0x75},
		{0xFB, 0x18, 0x0D, 0xAF, 0x48, 0xA7, 0x9E, 0xE0},
		{0xB1, 0x0D, 0x39, 0x46, 0x51, 0x85, 0x0F, 0xD4},
		{0xA1, 0x78, 0x89, 0x2E, 0xE2, 0x85, 0xEC, 0xE1},
		{0x51, 0x14, 0x55, 0x78, 0x08, 0x75, 0xD6, 0x4E},
	}

	runCodecEncodeTests(
		t, "BD1", tileconv.RowPlanar{BitDepth: tileconv.BD1},
		srcPix, []byte{
			0b10100100,
			0b11100110,
			0b01110010,
			0b00100111,
			0b10110100,
			0b11101110,
			0b10100101,
			0b10100100,
		},
	)

	runCodecEncodeTests(
		t, "BD2", tileconv.RowPlanar{BitDepth: tileconv.BD2},
		srcPix, []byte{
			0b10100100, 0b00011100,
			0b11100110, 0b01110110,
			0b01110010, 0b11011101,
			0b00100111, 0b01001010,
			0b10110100, 0b10010110,
			0b11101110, 0b00010010,
			0b10100101, 0b00011000,
			0b10100100, 0b00000011,
		},
	)

	runCodecEncodeTests(
		t, "BD3", tileconv.RowPlanar{BitDepth: tileconv.BD3},
		srcPix, []byte{
			0b10100100, 0b00011100, 0b01100110,
			0b11100110, 0b01110110, 0b00101000,
			0b01110010, 0b11011101, 0b11011011,
			0b00100111, 0b01001010, 0b00110101,
			0b10110100, 0b10010110, 0b00110110,
			0b11101110, 0b00010010, 0b01010111,
			0b10100101, 0b00011000, 0b00010110,
			0b10100100, 0b00000011, 0b01100111,
		},
	)

	runCodecEncodeTests(
		t, "BD4", tileconv.RowPlanar{BitDepth: tileconv.BD4},
		srcPix, []byte{
			0b10100100, 0b00011100, 0b01100110, 0b00101110,
			0b11100110, 0b01110110, 0b00101000, 0b00100101,
			0b01110010, 0b11011101, 0b11011011, 0b11110001,
			0b00100111, 0b01001010, 0b00110101, 0b11101110,
			0b10110100, 0b10010110, 0b00110110, 0b11111010,
			0b11101110, 0b00010010, 0b01010111, 0b01100010,
			0b10100101, 0b00011000, 0b00010110, 0b01110010,
			0b10100100, 0b00000011, 0b01100111, 0b00011001,
		},
	)

	runCodecEncodeTests(
		t, "BD5", tileconv.RowPlanar{BitDepth: tileconv.BD5},
		srcPix, []byte{
			0b10100100, 0b00011100, 0b01100110, 0b00101110, 0b01101010,
			0b11100110, 0b01110110, 0b00101000, 0b00100101, 0b01110110,
			0b01110010, 0b11011101, 0b11011011, 0b11110001, 0b00111000,
			0b00100111, 0b01001010, 0b00110101, 0b11101110, 0b00110001,
			0b10110100, 0b10010110, 0b00110110, 0b11111010, 0b11000010,
			0b11101110, 0b00010010, 0b01010111, 0b01100010, 0b10101001,
			0b10100101, 0b00011000, 0b00010110, 0b01110010, 0b01000000,
			0b10100100, 0b00000011, 0b01100111, 0b00011001, 0b11110110,
		},
	)

	// From here, we start writing the early planes as hex, since they
	// are the same as above and this allows us to fit more on a line.

	runCodecEncodeTests(
		t, "BD6", tileconv.RowPlanar{BitDepth: tileconv.BD6},
		srcPix, []byte{
			0xA4, 0x1C, 0x66, 0x2E, 0b01101010, 0b00101110,
			0xE6, 0x76, 0x28, 0x25, 0b01110110, 0b00100010,
			0x72, 0xDD, 0xDB, 0xF1, 0b00111000, 0b10101111,
			0x27, 0x4A, 0x35, 0xEE, 0b00110001, 0b11110101,
			0xB4, 0x96, 0x36, 0xFA, 0b11000010, 0b10010101,
			0xEE, 0x12, 0x57, 0x62, 0b10101001, 0b10100000,
			0xA5, 0x18, 0x16, 0x72, 0b01000000, 0b11011011,
			0xA4, 0x03, 0x67, 0x19, 0b11110110, 0b00010100,
		},
	)

	runCodecEncodeTests(
		t, "BD7", tileconv.RowPlanar{BitDepth: tileconv.BD7},
		srcPix, []byte{
			0xA4, 0x1C, 0x66, 0x2E, 0x6A, 0b00101110, 0b00111011,
			0xE6, 0x76, 0x28, 0x25, 0x76, 0b00100010, 0b11100111,
			0x72, 0xDD, 0xDB, 0xF1, 0x38, 0b10101111, 0b11111101,
			0x27, 0x4A, 0x35, 0xEE, 0x31, 0b11110101, 0b10011001,
			0xB4, 0x96, 0x36, 0xFA, 0xC2, 0b10010101, 0b10001001,
			0xEE, 0x12, 0x57, 0x62, 0xA9, 0b10100000, 0b00011001,
			0xA5, 0x18, 0x16, 0x72, 0x40, 0b11011011, 0b01001011,
			0xA4, 0x03, 0x67, 0x19, 0xF6, 0b00010100, 0b10110111,
		},
	)

	runCodecEncodeTests(
		t, "BD8", tileconv.RowPlanar{BitDepth: tileconv.BD8},
		srcPix, []byte{
			0xA4, 0x1C, 0x66, 0x2E, 0x6A, 0x2E, 0b00111011, 0b01111011,
			0xE6, 0x76, 0x28, 0x25, 0x76, 0x22, 0b11100111, 0b01100001,
			0x72, 0xDD, 0xDB, 0xF1, 0x38, 0xAF, 0b11111101, 0b00101011,
			0x27, 0x4A, 0x35, 0xEE, 0x31, 0xF5, 0b10011001, 0b10110000,
			0xB4, 0x96, 0x36, 0xFA, 0xC2, 0x95, 0b10001001, 0b10010111,
			0xEE, 0x12, 0x57, 0x62, 0xA9, 0xA0, 0b00011001, 0b10000101,
			0xA5, 0x18, 0x16, 0x72, 0x40, 0xDB, 0b01001011, 0b10101111,
			0xA4, 0x03, 0x67, 0x19, 0xF6, 0x14, 0b10110111, 0b00000010,
		},
	)
}

func TestRowPlanarDecode(t *testing.T) {
	// This uses the same pixel data as for the Encode test above.
	wantPix := [][]uint8{
		{0x01, 0x94, 0xFD, 0xC2, 0xFA, 0x2F, 0xFC, 0xC0},
		{0x41, 0xD3, 0xFF, 0x12, 0x04, 0x5B, 0x73, 0xC8},
		{0x6E, 0x4F, 0xF9, 0x5F, 0xF6, 0x62, 0xA5, 0xEE},
		{0xE8, 0x2A, 0xBD, 0xF4, 0x4A, 0x2D, 0x0B, 0x75},
		{0xFB, 0x18, 0x0D, 0xAF, 0x48, 0xA7, 0x9E, 0xE0},
		{0xB1, 0x0D, 0x39, 0x46, 0x51, 0x85, 0x0F, 0xD4},
		{0xA1, 0x78, 0x89, 0x2E, 0xE2, 0x85, 0xEC, 0xE1},
		{0x51, 0x14, 0x55, 0x78, 0x08, 0x75, 0xD6, 0x4E},
	}

	runCodecDecodeTests(
		t, "BD1", tileconv.RowPlanar{BitDepth: tileconv.BD1},
		[]byte{
			0b10100100,
			0b11100110,
			0b01110010,
			0b00100111,
			0b10110100,
			0b11101110,
			0b10100101,
			0b10100100,
		},
		pixBits(1, wantPix),
	)

	runCodecDecodeTests(
		t, "BD2", tileconv.RowPlanar{BitDepth: tileconv.BD2},
		[]byte{
			0b10100100, 0b00011100,
			0b11100110, 0b01110110,
			0b01110010, 0b11011101,
			0b00100111, 0b01001010,
			0b10110100, 0b10010110,
			0b11101110, 0b00010010,
			0b10100101, 0b00011000,
			0b10100100, 0b00000011,
		},
		pixBits(2, wantPix),
	)

	runCodecDecodeTests(
		t, "BD3", tileconv.RowPlanar{BitDepth: tileconv.BD3},
		[]byte{
			0b10100100, 0b00011100, 0b01100110,
			0b11100110, 0b01110110, 0b00101000,
			0b01110010, 0b11011101, 0b11011011,
			0b00100111, 0b01001010, 0b00110101,
			0b10110100, 0b10010110, 0b00110110,
			0b11101110, 0b00010010, 0b01010111,
			0b10100101, 0b00011000, 0b00010110,
			0b10100100, 0b00000011, 0b01100111,
		},
		pixBits(3, wantPix),
	)

	runCodecDecodeTests(
		t, "BD4", tileconv.RowPlanar{BitDepth: tileconv.BD4},
		[]byte{
			0b10100100, 0b00011100, 0b01100110, 0b00101110,
			0b11100110, 0b01110110, 0b00101000, 0b00100101,
			0b01110010, 0b11011101, 0b11011011, 0b11110001,
			0b00100111, 0b01001010, 0b00110101, 0b11101110,
			0b10110100, 0b10010110, 0b00110110, 0b11111010,
			0b11101110, 0b00010010, 0b01010111, 0b01100010,
			0b10100101, 0b00011000, 0b00010110, 0b01110010,
			0b10100100, 0b00000011, 0b01100111, 0b00011001,
		},
		pixBits(4, wantPix),
	)

	runCodecDecodeTests(
		t, "BD5", tileconv.RowPlanar{BitDepth: tileconv.BD5},
		[]byte{
			0b10100100, 0b00011100, 0b01100110, 0b00101110, 0b01101010,
			0b11100110, 0b01110110, 0b00101000, 0b00100101, 0b01110110,
			0b01110010, 0b11011101, 0b11011011, 0b11110001, 0b00111000,
			0b00100111, 0b01001010, 0b00110101, 0b11101110, 0b00110001,
			0b10110100, 0b10010110, 0b00110110, 0b11111010, 0b11000010,
			0b11101110, 0b00010010, 0b01010111, 0b01100010, 0b10101001,
			0b10100101, 0b00011000, 0b00010110, 0b01110010, 0b01000000,
			0b10100100, 0b00000011, 0b01100111, 0b00011001, 0b11110110,
		},
		pixBits(5, wantPix),
	)

	// From here, we start writing the early planes as hex, since they
	// are the same as above and this allows us to fit more on a line.

	runCodecDecodeTests(
		t, "BD6", tileconv.RowPlanar{BitDepth: tileconv.BD6},
		[]byte{
			0xA4, 0x1C, 0x66, 0x2E, 0b01101010, 0b00101110,
			0xE6, 0x76, 0x28, 0x25, 0b01110110, 0b00100010,
			0x72, 0xDD, 0xDB, 0xF1, 0b00111000, 0b10101111,
			0x27, 0x4A, 0x35, 0xEE, 0b00110001, 0b11110101,
			0xB4, 0x96, 0x36, 0xFA, 0b11000010, 0b10010101,
			0xEE, 0x12, 0x57, 0x62, 0b10101001, 0b10100000,
			0xA5, 0x18, 0x16, 0x72, 0b01000000, 0b11011011,
			0xA4, 0x03, 0x67, 0x19, 0b11110110, 0b00010100,
		},
		pixBits(6, wantPix),
	)

	runCodecDecodeTests(
		t, "BD7", tileconv.RowPlanar{BitDepth: tileconv.BD7},
		[]byte{
			0xA4, 0x1C, 0x66, 0x2E, 0x6A, 0b00101110, 0b00111011,
			0xE6, 0x76, 0x28, 0x25, 0x76, 0b00100010, 0b11100111,
			0x72, 0xDD, 0xDB, 0xF1, 0x38, 0b10101111, 0b11111101,
			0x27, 0x4A, 0x35, 0xEE, 0x31, 0b11110101, 0b10011001,
			0xB4, 0x96, 0x36, 0xFA, 0xC2, 0b10010101, 0b10001001,
			0xEE, 0x12, 0x57, 0x62, 0xA9, 0b10100000, 0b00011001,
			0xA5, 0x18, 0x16, 0x72, 0x40, 0b11011011, 0b01001011,
			0xA4, 0x03, 0x67, 0x19, 0xF6, 0b00010100, 0b10110111,
		},
		pixBits(7, wantPix),
	)

	runCodecDecodeTests(
		t, "BD8", tileconv.RowPlanar{BitDepth: tileconv.BD8},
		[]byte{
			0xA4, 0x1C, 0x66, 0x2E, 0x6A, 0x2E, 0b00111011, 0b01111011,
			0xE6, 0x76, 0x28, 0x25, 0x76, 0x22, 0b11100111, 0b01100001,
			0x72, 0xDD, 0xDB, 0xF1, 0x38, 0xAF, 0b11111101, 0b00101011,
			0x27, 0x4A, 0x35, 0xEE, 0x31, 0xF5, 0b10011001, 0b10110000,
			0xB4, 0x96, 0x36, 0xFA, 0xC2, 0x95, 0b10001001, 0b10010111,
			0xEE, 0x12, 0x57, 0x62, 0xA9, 0xA0, 0b00011001, 0b10000101,
			0xA5, 0x18, 0x16, 0x72, 0x40, 0xDB, 0b01001011, 0b10101111,
			0xA4, 0x03, 0x67, 0x19, 0xF6, 0x14, 0b10110111, 0b00000010,
		},
		wantPix,
	)
}
